# Numpy
1. It works with numbers
2. It can be useful in array of any dimensions.
3. It can hold capability of advanced operations

In [1]:
import numpy as np

In [2]:
numpy_array = np.array([5,3,4,6,8,2])

In [3]:
numpy_array

array([5, 3, 4, 6, 8, 2])

In [4]:
numpy_array.ndim

1

In [5]:
numpy_array.shape

(6,)

In [6]:
len(numpy_array)

6

In [7]:
numpy_array_2d = np.array([[5,6,7],[6,5,4]])

In [8]:
numpy_array_2d

array([[5, 6, 7],
       [6, 5, 4]])

In [9]:
numpy_array_2d.shape

(2, 3)

In [10]:
numpy_array_2d.ndim

2

In [11]:
numpy_array_3d = np.array([[1,2,3],[4,5,6],[3,4,2],[6,7,9]])

In [12]:
numpy_array_3d

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 2],
       [6, 7, 9]])

In [13]:
numpy_array_3d.ndim

2

In [14]:
numpy_array_3d.shape

(4, 3)

In [15]:
zero_array = np.zeros((3,4))

In [16]:
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
specific_array = np.full((3,3),6)

In [18]:
specific_array

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [21]:
f = np.arange(0,31,5)

In [22]:
f

array([ 0,  5, 10, 15, 20, 25, 30])

In [24]:
g = np.linspace(0,6,10)

In [25]:
g

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [26]:
 zero_array.reshape(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
specific_array.flatten()

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

# Make the use of API 

In [61]:
import requests
import pandas as pd
#import json

url = "https://datausa.io/api/data?drilldowns=Nation&measures=Population"

def get_data(url):
    response = requests.request("GET", url)
    if response.status_code == 200:
        data = response.json()
        data = data.get("data")
        source = data.get("source")
        data_list = []
        source_data = [] 
        for datum in data: 
            data_list.append({
                        "ID Nation" : datum.get("ID Nation"),
                        "Nation" : datum.get("Nation"),
                        "ID Year" : datum.get("ID Year"),
                        "Year" : datum.get("Year"),
                        "Population" : datum.get("Population"),
                        "Slug Nation" : datum.get("Slug Nation")
            })
        for source_ in source:
            source_data.append({
                "Measures" : source_.get("Measures"),
                "Name" : source_.get("name"),
                "Source Name" : source_.get("annotations").get("source_name"),
                "Dataset Name" : source_.get("annotations").get("dataset name"),
                "Table ID" : source_.get("annotations").get("table_id"),
                "Topic" : source_.get("annotations").get("topic"),
                "Subtopic" : source_.get("annotations").get("subtopic")
                
            })
        data_df = pd.DataFrame(data_list)
        source_df = pd.DataFrame(source_data)
        
        return data_df, source_df
            

In [54]:
print(response.status_code)

200


In [55]:
response.text

'{"data":[{"ID Nation":"01000US","Nation":"United States","ID Year":2022,"Year":"2022","Population":331097593,"Slug Nation":"united-states"},{"ID Nation":"01000US","Nation":"United States","ID Year":2021,"Year":"2021","Population":329725481,"Slug Nation":"united-states"},{"ID Nation":"01000US","Nation":"United States","ID Year":2020,"Year":"2020","Population":326569308,"Slug Nation":"united-states"},{"ID Nation":"01000US","Nation":"United States","ID Year":2019,"Year":"2019","Population":324697795,"Slug Nation":"united-states"},{"ID Nation":"01000US","Nation":"United States","ID Year":2018,"Year":"2018","Population":322903030,"Slug Nation":"united-states"},{"ID Nation":"01000US","Nation":"United States","ID Year":2017,"Year":"2017","Population":321004407,"Slug Nation":"united-states"},{"ID Nation":"01000US","Nation":"United States","ID Year":2016,"Year":"2016","Population":318558162,"Slug Nation":"united-states"},{"ID Nation":"01000US","Nation":"United States","ID Year":2015,"Year":"20

In [56]:
type(response.content)

bytes

In [57]:
data = response.json()

In [58]:
type(response.text)

str

In [59]:
data.keys()

dict_keys(['data', 'source'])

In [60]:
type(response.status_code)

int

In [ ]:
data_df